### ISSUE TITLE
GitHub button has an invalid address

### ISSUE THREAD

**Issue by EliasC** [bubify/frontend#11]
After linking to a GitHub account, the GitHub button in Bubify omits the slash between the base adress and the repo, giving an incorrect URL, e.g., https://github.com/IOOPM-UUabcd1234. This is a regression compared to previous instances.

**Comment by JonasNorlinder** [comment]
Append / to base url in Course as a hotfix

**Comment by EliasC** [comment]
Thanks! Fixed now!
